name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install APT Deps
      run: sudo apt -y install libudev-dev libasound2-dev
    - name: Check
      run: cargo check
    - name: Install Clippy
      run: rustup component add clippy
    - name: Clippy
      run: cargo clippy --no-deps
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
